#!/bin/bash


## 1) grep usese files only and we cannot use variables in it
## 2) use cmd substituion around a whole pipe instead of echo "hi" | a=$(wc -c)

echo -e "  ========linux user audit tool=========  \n"
printf "names%s      UID%s      shell\n"
printf "===%s        ===%s      ===\n"

superusers=""

for users in $(cat /etc/passwd | cut -d: -f1,3,7)
do
	echo -n "$(echo $users | cut -d: -f1)      "
	echo -n "$(echo $users | cut -d: -f2)      "
	echo "$(echo $users | cut -d: -f3)"
	uid=$(echo $users | cut -d: -f2)
	#if echo $users | grep "0" > /dev/null;then                        # this wasnt working
	if [[ $uid -eq 0 ]];then
		echo "warning!!!!! this users have root access : $users"
	fi
done

echo "total users : "$(cat /etc/passwd | wc -l)""

if sorted_users=$(grep -vE "login|false" /etc/passwd | cut -d: -f1);then
	echo "accounts we can log in : "$sorted_users""
	total=$(echo "$sorted_users" | wc -w)
	echo "interactive users : $total"
fi

if unhuman=$(grep -E "login|false" /etc/passwd | wc -l);then
	echo "non interactive users : $unhuman"
fi
